# Generated by Django 2.2.5 on 2020-02-21 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("client_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "client_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dropbox_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bitly_url", models.CharField(blank=True, max_length=255, null=True)),
                ("crm_url", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("ready", models.IntegerField(blank=True, null=True)),
                ("active", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "audantic_clients", "managed": False,},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="login_registration.Client",
                    ),
                ),
            ],
        ),
    ]
