# Generated by Django 2.2.5 on 2020-03-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_super",
            field=models.BooleanField(default=False),
        ),
    ]
