# Generated by Django 2.2.5 on 2020-04-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_registration", "0003_auto_20200323_2110"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="client",),
        migrations.AddField(
            model_name="user",
            name="client_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
