# Generated by Django 2.2.5 on 2020-04-22 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_registration", "0004_auto_20200421_2046"),
    ]

    operations = [
        migrations.DeleteModel(name="Client",),
    ]
