# Generated by Django 2.2.5 on 2020-07-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_registration", "0005_delete_client"),
    ]

    operations = [
        migrations.AlterModelTable(name="user", table="portal_users",),
    ]
