# Generated by Django 2.2.5 on 2020-07-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_registration", "0006_auto_20200710_1836"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
