# Generated by Django 2.2.5 on 2020-10-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_registration", "0008_auto_20200710_2311"),
    ]

    operations = [
        migrations.AlterModelTable(name="user", table=None,),
    ]
