# Generated by Django 2.2.5 on 2021-06-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0010_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
