# Generated by Django 2.2.5 on 2021-06-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0011_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
