# Generated by Django 2.2.5 on 2021-07-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0013_user_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
