# Generated by Django 2.2.5 on 2021-07-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0014_remove_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_regions', models.IntegerField(default=1)),
                ('max_users', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=False)),
                ('skip_credits', models.IntegerField(default=200)),
                ('env_access', models.CharField(default='prod', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
    ]
