# Generated by Django 2.2.5 on 2021-08-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0015_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_buyersonar_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_liveloop_user',
            field=models.BooleanField(default=True),
        ),
    ]
