# Generated by Django 2.2.5 on 2020-02-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_auto_20200224_2347"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZipExclude",
            fields=[
                ("index", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "region_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("zip", models.CharField(blank=True, max_length=5, null=True)),
                ("client", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"db_table": "sfr_zip_exclude", "managed": False,},
        ),
    ]
