# Generated by Django 2.2.5 on 2020-04-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0003_zipexclude"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("client_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "client_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dropbox_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bitly_url", models.CharField(blank=True, max_length=255, null=True)),
                ("crm_url", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("ready", models.IntegerField(blank=True, null=True)),
                ("active", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "audantic_clients", "managed": False,},
        ),
    ]
