# Generated by Django 2.2.5 on 2020-05-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0004_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="HasAttribution",
            fields=[
                ("region_id", models.IntegerField(primary_key=True, serialize=False)),
                ("year_qtr", models.CharField(max_length=6)),
                ("active", models.BooleanField()),
            ],
            options={"db_table": "audantic_regions_attribution", "managed": False,},
        ),
    ]
