# Generated by Django 2.2.5 on 2021-01-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0006_regionsettingslog"),
    ]

    operations = [
        migrations.DeleteModel(name="RegionSettingsLog",),
    ]
