# Generated by Django 3.1.7 on 2021-03-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_delete_regionsettingslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasDeliveryDate',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year_qtr', models.CharField(max_length=6)),
                ('delivery_date', models.DateField()),
            ],
            options={
                'db_table': 'live_loop_delivery_dates',
                'managed': False,
            },
        ),
    ]
